/* eslint-disable import/no-extraneous-dependencies */
import React from "react"
import '../styles/test3.modules.css'


export default function App(){
        return (
          <div className="container">
            <div className="child">
              <h3 className="w-32">Section 1</h3>
              <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eros donec ac odio tempor. Sed enim ut sem viverra aliquet eget sit. Maecenas sed enim ut sem viverra aliquet. Nullam non nisi est sit amet facilisis magna. Purus sit amet volutpat consequat. Elementum tempus egestas sed sed risus. Nibh mauris cursus mattis molestie a. Leo in vitae turpis massa. Leo in vitae turpis massa sed elementum tempus. Viverra vitae congue eu consequat ac felis donec et odio. Orci ac auctor augue mauris augue neque gravida. In mollis nunc sed id semper risus. Sed lectus vestibulum mattis ullamcorper velit sed. Lacinia quis vel eros donec ac. Leo urna molestie at elementum eu facilisis.

Aliquet bibendum enim facilisis gravida. Aenean pharetra magna ac placerat vestibulum lectus mauris. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed velit. Dui accumsan sit amet nulla facilisi morbi tempus iaculis urna. Mauris cursus mattis molestie a iaculis at erat pellentesque. Nec feugiat in fermentum posuere urna. A diam sollicitudin tempor id eu. Libero nunc consequat interdum varius sit amet mattis. Sit amet tellus cras adipiscing enim eu turpis. Nunc sed blandit libero volutpat sed cras. Enim diam vulputate ut pharetra sit amet. Est ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Ultrices dui sapien eget mi proin sed libero. Purus sit amet luctus venenatis lectus magna fringilla urna porttitor. Eget lorem dolor sed viverra ipsum nunc aliquet. Ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel.

Tristique senectus et netus et malesuada fames. Dignissim suspendisse in est ante in. Rutrum quisque non tellus orci ac auctor augue mauris augue. Neque convallis a cras semper auctor neque. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Purus semper eget duis at tellus at urna condimentum mattis. Sed felis eget velit aliquet. Cras sed felis eget velit aliquet sagittis id. Egestas fringilla phasellus faucibus scelerisque. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Elementum integer enim neque volutpat ac. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. Nisl condimentum id venenatis a condimentum. Placerat duis ultricies lacus sed turpis tincidunt id. Ut sem nulla pharetra diam sit. Nulla facilisi morbi tempus iaculis urna. Laoreet suspendisse interdum consectetur libero id.

Adipiscing commodo elit at imperdiet dui accumsan sit. Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Tincidunt vitae semper quis lectus nulla at volutpat diam. Sed vulputate mi sit amet. Sed risus pretium quam vulputate dignissim suspendisse in est ante. Justo nec ultrices dui sapien eget mi proin. Aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Justo laoreet sit amet cursus sit. Tristique sollicitudin nibh sit amet commodo nulla. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum varius. Cras pulvinar mattis nunc sed blandit. Turpis massa sed elementum tempus. Magna ac placerat vestibulum lectus mauris ultrices eros. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh. Cursus risus at ultrices mi tempus imperdiet. Eget gravida cum sociis natoque penatibus et magnis dis parturient. Tempor orci eu lobortis elementum nibh tellus molestie. Velit ut tortor pretium viverra suspendisse potenti.

Interdum consectetur libero id faucibus nisl tincidunt. Scelerisque fermentum dui faucibus in ornare quam viverra orci sagittis. Proin sed libero enim sed faucibus turpis in. Aliquam eleifend mi in nulla posuere. Interdum velit laoreet id donec. Placerat vestibulum lectus mauris ultrices eros in. Non consectetur a erat nam at lectus urna duis convallis. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros in. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor eu. Cras ornare arcu dui vivamus arcu felis bibendum ut. Accumsan sit amet nulla facilisi morbi tempus iaculis urna. Magna sit amet purus gravida quis. Amet est placerat in egestas erat imperdiet. Et magnis dis parturient montes nascetur ridiculus mus. Mollis nunc sed id semper. Augue ut lectus arcu bibendum at varius vel pharetra vel.
              </p>
            </div>
            <div className="">
              
            </div>
            <div className="child">
              <h3 className="text-cyan">Section 3</h3>
              <p>
              Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Eros donec ac odio tempor. Sed enim ut sem viverra aliquet eget sit. Maecenas sed enim ut sem viverra aliquet. Nullam non nisi est sit amet facilisis magna. Purus sit amet volutpat consequat. Elementum tempus egestas sed sed risus. Nibh mauris cursus mattis molestie a. Leo in vitae turpis massa. Leo in vitae turpis massa sed elementum tempus. Viverra vitae congue eu consequat ac felis donec et odio. Orci ac auctor augue mauris augue neque gravida. In mollis nunc sed id semper risus. Sed lectus vestibulum mattis ullamcorper velit sed. Lacinia quis vel eros donec ac. Leo urna molestie at elementum eu facilisis.

Aliquet bibendum enim facilisis gravida. Aenean pharetra magna ac placerat vestibulum lectus mauris. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed velit. Dui accumsan sit amet nulla facilisi morbi tempus iaculis urna. Mauris cursus mattis molestie a iaculis at erat pellentesque. Nec feugiat in fermentum posuere urna. A diam sollicitudin tempor id eu. Libero nunc consequat interdum varius sit amet mattis. Sit amet tellus cras adipiscing enim eu turpis. Nunc sed blandit libero volutpat sed cras. Enim diam vulputate ut pharetra sit amet. Est ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Ultrices dui sapien eget mi proin sed libero. Purus sit amet luctus venenatis lectus magna fringilla urna porttitor. Eget lorem dolor sed viverra ipsum nunc aliquet. Ridiculus mus mauris vitae ultricies leo integer malesuada nunc vel.

Tristique senectus et netus et malesuada fames. Dignissim suspendisse in est ante in. Rutrum quisque non tellus orci ac auctor augue mauris augue. Neque convallis a cras semper auctor neque. Sapien faucibus et molestie ac feugiat sed lectus vestibulum. Purus semper eget duis at tellus at urna condimentum mattis. Sed felis eget velit aliquet. Cras sed felis eget velit aliquet sagittis id. Egestas fringilla phasellus faucibus scelerisque. Nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur vitae. Elementum integer enim neque volutpat ac. Cursus in hac habitasse platea dictumst quisque sagittis purus sit. Nisl condimentum id venenatis a condimentum. Placerat duis ultricies lacus sed turpis tincidunt id. Ut sem nulla pharetra diam sit. Nulla facilisi morbi tempus iaculis urna. Laoreet suspendisse interdum consectetur libero id.

Adipiscing commodo elit at imperdiet dui accumsan sit. Tincidunt praesent semper feugiat nibh sed pulvinar proin gravida. Tincidunt vitae semper quis lectus nulla at volutpat diam. Sed vulputate mi sit amet. Sed risus pretium quam vulputate dignissim suspendisse in est ante. Justo nec ultrices dui sapien eget mi proin. Aliquam eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis. Justo laoreet sit amet cursus sit. Tristique sollicitudin nibh sit amet commodo nulla. Tincidunt lobortis feugiat vivamus at augue eget arcu dictum varius. Cras pulvinar mattis nunc sed blandit. Turpis massa sed elementum tempus. Magna ac placerat vestibulum lectus mauris ultrices eros. Platea dictumst quisque sagittis purus sit amet volutpat consequat mauris. Nisl nisi scelerisque eu ultrices vitae auctor eu augue ut. Aliquam nulla facilisi cras fermentum odio eu feugiat pretium nibh. Cursus risus at ultrices mi tempus imperdiet. Eget gravida cum sociis natoque penatibus et magnis dis parturient. Tempor orci eu lobortis elementum nibh tellus molestie. Velit ut tortor pretium viverra suspendisse potenti.

Interdum consectetur libero id faucibus nisl tincidunt. Scelerisque fermentum dui faucibus in ornare quam viverra orci sagittis. Proin sed libero enim sed faucibus turpis in. Aliquam eleifend mi in nulla posuere. Interdum velit laoreet id donec. Placerat vestibulum lectus mauris ultrices eros in. Non consectetur a erat nam at lectus urna duis convallis. Pharetra magna ac placerat vestibulum lectus mauris ultrices eros in. Accumsan in nisl nisi scelerisque eu ultrices vitae auctor eu. Cras ornare arcu dui vivamus arcu felis bibendum ut. Accumsan sit amet nulla facilisi morbi tempus iaculis urna. Magna sit amet purus gravida quis. Amet est placerat in egestas erat imperdiet. Et magnis dis parturient montes nascetur ridiculus mus. Mollis nunc sed id semper. Augue ut lectus arcu bibendum at varius vel pharetra vel.
              </p>
            </div>
          </div>
        )

        }

